name: Server Docker Image CI

on:
  workflow_dispatch:
  push:
    branches: ["current"]
    paths:
      - "server/**"

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ${{ secrets.DOCKERHUB_USERNAME }}/banpay-challenge
          tags: |
            type=raw,value=latest,priority=100
            type=sha,enable=true,priority=200,prefix=sha-,suffix=,format=short
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          platforms: linux/amd64
          context: "{{ defaultContext }}:server"
          file: Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
